"""create first db

Revision ID: eee789cb3a5e
Revises: 
Create Date: 2026-07-04 06:27:54.499049
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'eee789cb3a5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
